config/routes.rb
Rails.application.routes.draw do
  
  get 'page/home'
  get 'page/about_us'
  post 'page/about_us'
  get 'page/recipes'
  get 'page/products'
  get 'page/blog'
  get 'page/login'

  root 'page#home'
  get 'page/calendar(/:year(/:month))' => 'page#calendar', as: :page_calendar

  
  resources :say

end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id          :integer          not null, primary key
#  name        :string
#  serves      :integer
#  ingredients :text
#  made_by     :string
#  last_made   :datetime
#  image       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Recipe < ActiveRecord::Base
  attr_accessor :name, :serves, :ingredients, :made_by, :last_made, :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  
  before_action :setup

  def home
  end

  def about_us
    # flash[:notice] = "Hey, Dave, you can't do that"
    @name = params[:name]
    @email = params[:email]

    if params[:commit]
      flash.now[:error] = ""
      if @name.nil? || @name.empty?
        flash.now[:error] << "Name cannot be blank. <br />"
      end
      if @email.nil? || @email.empty?
        flash.now[:error] << "Email cannot be blank. <br />"
      end
    end
    
    @age = params[:age]
    @comments = params[:comments]
    @products = %w(Skiis poles mittens)
    @selected_product = params[:count]
    @food = params[:food]
  end

  def recipes
    @recipes = Recipe.all
  end

  def products
    @products = ['skiis' => 199.99 ]
  end

  def calendar
    @year = params[:year]
    @month = params[:month]
    @name = "Lino Espinoza"
    @my_time = Time.now
    @products = %w(Skiis boots poles mittens) # = ["Skiis", "boots", "poles", "mittens"]
  end

  def blog
  end

  def login
  end

  def setup
    @products = { 1 => 'Skiis', 2 => 'boots', 3 => 'poles', 4 => 'mittens' , 5 => 'mask', 6 => 'hat', 7 => 'mask' }
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_params()
    html = "<div>"
    html += "<h1>Params</h1><code>"
    params.each do |key, value|
      html += "#{key}: #{value}<br/>" if(key != 'authenticity_token' && key != 'utf8')
    end
    html += "</code></div>"
    return html.html_safe
  end

  def things_to_do(links)
    # key = URL, value = body
    html = "<ul>\n"
    links.each do |url, body|
      html += "\t<li>" + link_to(body, url)+ "</li>\n"
    end
    html += "</ul>\n"
    return html.html_safe
  end

  def calendar(month, year)
    prev_month = link_to "Previous", page_calendar_path(:month => month.to_i - 1, :year => year) 
    cal_str = "<table border='1'>"
    cal_str = "<tr><td>#{prev_month}</td><td colspan='7'>October</td></tr>"
    cal_str += "<tr>"
    cal_str += "<td>&nbsp;</td>"
    6.times do |day|
      cal_str += "<td>#{day + 1}</td>"
    end
    cal_str += "</tr>"
    cal_str += "</table>"
    cal_str.html_safe
  end

end

app/helpers/page_helper.rb
module PageHelper

end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag 'application-all', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application-print', media: 'print', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tag %>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
<div id="wrapper"><!-- #wrapper -->

  <nav><!-- top nav -->
    <%= render partial: 'shared/navigation' %>
  </nav><!-- end of top nav -->

  <header><!-- header -->
    <h1><a href="#">Blinded by Science</a></h1>
    <h2>Your interesting tag line goes here</h2>
  </header><!-- end of header -->

  <section id="main"><!-- #main content and sidebar area -->
    <section id="content"><!-- #content -->
        <div style="border: 1px solid red">
          <% if flash[:notice] %>
            <p class="notice"><%= flash[:notice].html_safe %></p>
          <% end %>
          <% if flash[:error] %>
            <p class="error"><%= flash[:error].html_safe %></p>
          <% end %>
        </div>
        <%= yield %>
    </section><!-- end of #content -->

    <aside id="sidebar"><!-- sidebar -->
      <h3>Things To Do</h3>
      <%= things_to_do( 'http://www.google.com' => 'www.google.com', 
                        'http://www.lmgtfy.com' => 'lmgtfy',
                        'http://www.facebook.com' => 'www.facebook.com',
                        page_calendar_path => 'Events' ) %>

      <h3>Sponsors</h3>
      <%= image_tag 'ad125.jpg', alt: 'Ad125 Image' %><br />
      <%= image_tag "ad125.jpg", :alt => "Ad125 Image" %><br /><br />

      <h3>Connect With Us</h3>
      <ul>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">Facebook</a></li>
      </ul>

    </aside><!-- end of sidebar -->

  </section><!-- end of #main content and sidebar-->

  <footer>
    <section id="footer-area">

      <section id="footer-outer-block">
        <aside class="footer-segment">
          <h4>Friends</h4>
          <ul>
            <li><a href="#">one linkylink</a></li>
            <li><a href="#">two linkylinks</a></li>
            <li><a href="#">three linkylinks</a></li>
          </ul>
        </aside><!-- end of #first footer segment -->

        <aside class="footer-segment">
          <h4>Awesome Stuff</h4>
          <ul>
            <li><a href="#">one linkylink</a></li>
            <li><a href="#">two linkylinks</a></li>
            <li><a href="#">three linkylinks</a></li>
          </ul>
        </aside><!-- end of #second footer segment -->

        <aside class="footer-segment">
          <h4>Coolness</h4>
          <ul>
            <li><a href="#">one linkylink</a></li>
            <li><a href="#">two linkylinks</a></li>
            <li><a href="#">three linkylinks</a></li>
          </ul>
        </aside><!-- end of #third footer segment -->

        <aside class="footer-segment">
          <h4>Blahdyblah</h4>
          <p>&copy; 2015 <a href="#">yoursite.com</a> Praesent libero. Sed cursus ante dapibus diam. Sed nisi.</p>
        </aside><!-- end of #fourth footer segment -->

      </section><!-- end of footer-outer-block -->

    </section><!-- end of footer-area -->
  </footer>

</div><!-- #wrapper -->
</body>
</html>

app/views/page/about_us.html.erb
<% content_for 'title' do %>
  About us
<% end %>

<h1>Ask a Question</h1>

<%= form_tag do %>
  <%= field_set_tag 'Information' do %>
    <p>
      <%= label_tag 'name', 'Name:' %>
      <%= text_field_tag 'name', @name, class: 'input', placeholder: 'Enter a name', size: 50 %>
    </p>

    <p>
      <%= label_tag 'email', 'Email Address:' %>
      <%= email_field_tag 'email', @email, placeholder: 'Enter an email', size: 64 %>
    </p>

    <p>
      <%= label_tag 'age', 'Age:' %>
      <%= number_field_tag 'age', @age, placeholder: 'Enter your age', min: 10, max: 20 %>
    </p>

    <p>
      <%= label_tag 'product', 'product:' %>
      <%#= select_tag 'product', options_for_select( @products.map { |value| [value, value]}, @selected_product) %>
      <%= select_tag 'product', options_for_select( @products, @selected_product) %>
    </p>
 
    <p>
      <%= label_tag 'food_salad', 'Salad' %>
      <%= radio_button_tag 'food', 'salad', @food == 'salad' %>

      <%= label_tag 'food_main', 'Main' %>
      <%= radio_button_tag 'food', 'main', @food == 'main' %>

      <%= label_tag 'food_dessert', 'Dessert' %>
      <%= radio_button_tag 'food', 'dessert', @food == 'dessert' %>
    </p>

    <p>
      <%= label_tag 'comments', 'Comments:' %>
      <%= text_area_tag 'comments', @comments %>
    </p>

    <p><%= submit_tag 'Submit your question' %></p>
  <% end %>
<% end %>

<% @products.each do |key, value| %>
  <%= key.to_s + ' ' + value.to_s %>
<% end %>

<% if params[:commit] != nil %>
  <%= show_params %>
<% end %>

app/views/page/blog.html.erb
<h1>Page#blog</h1>
<p>Find me in app/views/page/blog.html.erb</p>

app/views/page/calendar.html.erb
<h1>Page#calendar</h1>
<p>Find me in app/views/page/calendar.html.erb</p>

<p><%= @name + ' ' + @my_time.to_s %></p>

<p><b><%= @year + '/' + @month %> products</b></p>

<%= calendar(@month, @year) %>

<ul>
<% @products.each do |product| %>
    <li><%= product.capitalize %></li>
<% end %>
</ul>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/page/login.html.erb
<h1>Page#login</h1>
<p>Find me in app/views/page/login.html.erb</p>

app/views/page/products.html.erb
<h1>Page#products</h1>
<p>Find me in app/views/page/products.html.erb</p>

app/views/page/recipes.html.erb
<h1>Page#recipes</h1>
<p>Find me in app/views/page/recipes.html.erb</p>

<% @recipes.each do |recipe| %>
    <section>
        <heading><%= recipe.name %></heading>
        Made by: <%= recipe.made_by %><br />
        Serves: <%= recipe.serves %><br />
        Last_made: <%= recipe.last_made %><br />
    </section>
<% end %>

app/views/shared/_navigation.html.erb
<div class="menu">
  <ul>
    <li><%= link_to_unless_current "Home", page_home_path %></li>
    <li><%= link_to_unless_current "About Us", page_about_us_path %></li>
    <li><%= link_to_unless_current "Recipes", page_recipes_path %></li>
    <li><%= link_to_unless_current "Products", page_products_path %></li>
    <li><%= link_to_unless_current "Calendar", page_calendar_path %></li>
    <li><%= link_to_unless_current "Blog", page_blog_path %></li>
    <li><%= link_to_unless_current "Login", page_login_path %></li>
  </ul>
</div>